### ISSUE TITLE
Helium on Android does not recognize root

### ISSUE THREAD

**Issue by Nippey** [koush/support-wiki#138]
Hi,

I just installed the Helium app on my S6+Nemesis ROM.

Unfortunately I can neither enable Helium by :
* The Window Application (latest drivers installed, debugging active, both S6+Win rebooted)
* MagiskSU (Magist v13.2, Magisk Manager 5.0.6)

Is there any way to manually enable it via Terminal Emulator?

Regards!

**Comment by MrCrayon** [comment]
I have a similar problem, root is not recognised.
Carbon Desktop app runs a script on the device through adb so the solution is to run the script directly on the device.
I stripped the adb part from run.sh found in carbon-linux.tgz and I got this working shell script:
`pkg=$(pm path com.koushikdutta.backup)`
`pkg=$(echo $pkg | cut -d : -f 2 | sed s/\\r//g)`
`echo $pkg`
`CLASSPATH=$pkg app_process /system/bin com.koushikdutta.shellproxy.ShellRunner2 $@ &`
Save the file in your sdcard and the run as su from terminal:
`sh /sdcard/name_of_your_script_file`
After that you can run the app and it should not ask for desktop connection anymore, it worked for me.
I think you need to run this again if you restart your phone.

**Comment by Nippey** [comment]
Hey, thanks for the hint.
I already took the chrome extension apart and tried something similar:

(CLASSPATH=/data/app/com.koushikdutta.backup-1/base.apk /system/bin/app_process32 /system/bin com.koushikdutta.shellproxy.ShellRunner2 > /dev/null ; sleep 30) &
This only helped partially:
I could run Helium, but I could only backup SMS/WiFi-Passwords/Dictionary.
I was not able to backp any APK or DATA.

I will try your variant tonight!

**Comment by Nippey** [comment]
@MrCrayon your solution is working, awesome! 👍

**Comment by Iruberiam** [comment]
This did the job, thanks.

**Comment by freMea** [comment]
It's a workaround but the android app still needs to fix the undetected root issue.

relative issue : #111, #174, #138, #116
