### ISSUE TITLE
helium not backing up anywhere, all is 'error occurred'

### ISSUE THREAD

**Issue by viennades** [koush/support-wiki#17]
I had no trouble with this app at first. Now I'm getting the 'error occurred' message, no matter where I try to back it up -- clouds, external, all the same error. I've tried backing up just 1 app, data only, still no joy. I've tried connecting in different sequences. The device is not encrypted and firmware hasn't been updated or otherwise changed. Desktop and Android seem to connect just fine. Help? I have the Pro version, Samsung Note 10.1, desktop is running Windows 7. 
Thanks, Vie

**Comment by jbrown123** [comment]
I have a similar experience.  If I enable any app for backup (either the app or just app data) I get the "An error occurred while performing your app backup. ..." message.  If I ONLY turn on the messaging store and the user dictionary, I can complete a backup successfully.  If any app is included, it fails.

**Comment by kevinbakon** [comment]
The same thing is happening to me and despite my best efforts, I cannot find a solution online, anywhere.... I've been using this app for years to backup, restore and switch between phones, but now I simply cannot get it to work... The error message reads "An error occurred while performing your app backup. A log of the error has been sent to ClockworkMod. Click Backup to attempt to backup the remaining apps."

**Comment by denzor33** [comment]
Koush,  What is the explanation for closing this issue?  Has it been corrected somehow?  If so how do I proceed when I get the error?  I am getting this error as well and I have also been successful using Helium for backing up apps in the past but now I get this error.  I am experiencing the exact same symptoms as kevinbakon.  Please respond and let us know what is going on with this issue.

**Comment by RFish22** [comment]
I just paid for Premium and am receiving the same error! I have a new phone that is a brick w/o the backup. Any help?
