### ISSUE TITLE
AllCast does not detect Rygel DLNA Server

### ISSUE THREAD

**Issue by mfulgo** [koush/support-wiki#18]
I have Rygel running as a DLNA server on my desktop. The Video player built into my Samsung Galaxy Tab 3 is able to see and play the files just fine. However, when I select (tv) Media Server from the list in AllCast (on the same device), it just sits at the "Loading..." screen, spinning. 

Thoughts? Can I collect any kind of logs to help debug this? 

Thanks, 
Matt

**Comment by chossimbaone** [comment]
I Have the same issue with my attached usb disk to my router, the Media server is just loading for ever. Works fine from bubbleupnp.
