### ISSUE TITLE
Helium backup process stalls if a backup password has been set

### ISSUE THREAD

**Issue by seanf** [koush/support-wiki#3]
If a backup password has been set, there is a brief switch to the "backup password" screen when first attempting a backup, but it disappears quickly.  After that, any attempts to start a backup just freeze with no explanation, unless the password is removed.  You might want to put something about this in the FAQ.

**Comment by Spyder918** [comment]
Same or similar problem Helium on S7 Edge opens and when backup starts it wants to verify that no desktop password exists.  It doesn't but there is anything I've tried that will satisfy it.  Hence, no backup.  I want to see this work before purchasing.
