### ISSUE TITLE
Android N - No Backup or Restore

### ISSUE THREAD

**Issue by simongabriel** [koush/support-wiki#57]
Currently running the latest Beta version for Android N on Nexus 5X. Helium gets jammed when trying to backup an app and gets stuck around 92% when trying to restore app.

Worked fine running Marshmallow on same device.

**Comment by TurboFool** [comment]
Having the same problems on a Nexus 6. Just loops during the backup process, demanding an encryption password, but even if I create one in settings, it does the same.

**Comment by rprimus** [comment]
Mon Jul  4 10:41:36 BST 2016

```
device:  Nexus 5X
build: NPD56N
encryption: on
rooted: no
```

1. Device is currently set up to be unlocked using a pattern.
2. Changed this in settings to use a PIN
3. Entered PIN in Helium/Carbon > Settings
4. When attempting a backup, note stating device is encrypted and 'please enter  **a** password'.
5 .Enter PIN, then sent to screen ```Password or PIN```.
6. Upon entering PIN, sent back to ```Full Backup``` screen ```(Step 4)```
7. To break cycle/loop, select ```DO NOT BACK UP```

**Comment by simongabriel** [comment]
@rprimus 

Sorry, I'm a little confused. Are you suggesting this as a fix? The method you have displayed, does that allow Helium to work on Android N?

**Comment by rprimus** [comment]
Mon Jul  4 12:14:09 BST 2016

@simongabriel 

No,  this is not a fix. I'm just detailing my experience - expanding on the post by @TurboFool.

Will edit post to clarify.

**Comment by rprimus** [comment]
Mon Jul  4 12:41:35 BST 2016

This looks to be a **bug** in Android N.

I've just attempted to do a full adb backup.  After entering the desktop password,  a few apps were backed up and then progress halted.

```adb devices``` then showed no devices connected.

**Conclusion**

adb appears to die shortly after a backup is started.

**Comment by rprimus** [comment]
Mon Jul  4 13:25:53 BST 2016

Was too hasty above.   Have successfully completed two adb backups:
1.  With a backup password set
2.  Other without a backup password set.

Returning to Helium/Carbon,  a similar experience occurred. 
**[Carbon appears to require that no desktop password be set.]**

[For clarification,  the first password screen that shows up (same as in ```adb backup```) is for user to set a per-backup password - to encrypt the **current** backup file (being created).]

At this point, the process hung - not being asked to enter the device's ```encryption password or PIN```.

Attempting a backup of 4 apps to ```Internal Storage```:

adb logcat:
```
07-04 13:23:39.078   439  7296 I CarbonShell: Command: bu backup  org.agentstats com.tapslash.android.latin com.gabemart.asoftmurmur com.jnj.sevenminuteworkout
07-04 13:23:39.093  7042  7293 I Carbon  : Demux atomic: false
07-04 13:23:42.102  7042  7321 I Carbon  : dims: 1080 1794
07-04 13:23:42.112   439   439 I CarbonShell: Got socket
07-04 13:23:42.122   439  7323 I CarbonShell: Command: sh
07-04 13:24:40.303   439  7296 I CarbonShell: exiting
07-04 13:24:40.304   439  7296 I CarbonShell: exit: bu backup  org.agentstats com.tapslash.android.latin com.gabemart.asoftmurmur com.jnj.sevenminuteworkout
07-04 13:24:40.304   439  7296 I CarbonShell: 0
07-04 13:24:40.304   439  7296 I CarbonShell: exit written
07-04 13:24:40.327   439  7299 I CarbonShell: error
07-04 13:24:40.327   439  7299 I CarbonShell: java.net.SocketException: Socket closed
07-04 13:24:40.327   439  7299 I CarbonShell: 	at java.net.SocketInputStream.socketRead0(Native Method)
07-04 13:24:40.327   439  7299 I CarbonShell: 	at java.net.SocketInputStream.read(SocketInputStream.java:151)
07-04 13:24:40.327   439  7299 I CarbonShell: 	at java.net.SocketInputStream.read(SocketInputStream.java:120)
07-04 13:24:40.327   439  7299 I CarbonShell: 	at java.net.SocketInputStream.read(SocketInputStream.java:206)
07-04 13:24:40.327   439  7299 I CarbonShell: 	at java.io.DataInputStream.readInt(DataInputStream.java:387)
07-04 13:24:40.327   439  7299 I CarbonShell: 	at com.koushikdutta.shellproxy.ShellRunner2$1$1.run(ShellRunner2.java:64)
07-04 13:24:40.335  7042  7293 I Carbon  : Releasing locks.
07-04 13:24:40.336   866 10748 D WifiService: releaseWifiLockLocked: WifiLock{Carbon type=1 uid=10240}
07-04 13:24:40.337  7042  7042 I Carbon  : Stopping.
```

**Comment by simongabriel** [comment]
@rprimus Thanks for doing all of this research. Not sure if it's a good thing or not that It's N's problem. I'm not extremely technical, so forgive this question sounding naive, would this be on the agenda for Android to fix? Or is there a chance N would go live and this issue still exist?

I really wanted to stick with the Beta on my 5X, but I use Helium on a daily basis

**Comment by rprimus** [comment]
Mon Jul  4 13:46:57 BST 2016

Just noticed this in the logcat:

```
07-04 13:20:15.975   866 17601 D BackupManagerService: Waiting for full backup completion...$
   8 07-04 13:20:16.156  5597  5597 E BackupRestoreConfirmation: Unable to communicate with mount service: no permission to access the crypt keeper: Neither user 10000 nor current process has android.      permission.STORAGE_INTERNAL.$
```

If you can get @koush  to look here, this may solve the problem.

**Comment by simongabriel** [comment]
@rprimus Brilliant. 

I've emailed Clockworkmod support in the hope to have @koush or anyone else see this.

**Comment by koush** [comment]
Working on this now.

**Comment by simongabriel** [comment]
Fantastic! I'm currently on Android M but will upgrade again to Beta if you
manage to fix and let you know

On Mon, Jul 4, 2016, 19:15 Koushik Dutta <notifications@github.com> wrote:

> Working on this now.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/koush/support-wiki/issues/57#issuecomment-230336483>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASkMH7lutZppFFkvn__aNXyga9jiUa_kks5qSU2sgaJpZM4IiHtF>
> .
>
-- 
www.s-gabriel.com
instagram.com/simonpatrickgabriel

**Comment by koush** [comment]
The issue I am running into is that key automation seems broken on Android N. Worked fine in M. Not sure what's up.

**Comment by simongabriel** [comment]
Hmm. So you think the issue could be Android N? Something they'll likely
fix? I wonder if others have faced automation issues

On Mon, Jul 4, 2016, 19:17 Koushik Dutta <notifications@github.com> wrote:

> The issue I am running into is that key automation seems broken on Android
> N. Worked fine in M. Not sure what's up.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/koush/support-wiki/issues/57#issuecomment-230336654>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASkMH9m2EdhipuQlBsvwbJKVqsRXyf1Pks5qSU4egaJpZM4IiHtF>
> .
>
-- 
www.s-gabriel.com
instagram.com/simonpatrickgabriel

**Comment by koush** [comment]
The actual backup and restore process seems to be functioning correctly on the latest version of N. I recall it being broken before, which is why I never got around to doing anything about it.

The key automation is something I'll need to fix. Worst case scenario, users will need to enter the password on Android N.

**Comment by simongabriel** [comment]
Oh that's not so bad. When I tried this in May I couldn't actually get a
restore to work at all. So basically it will work if I can set a key?

On Mon, Jul 4, 2016, 19:20 Koushik Dutta <notifications@github.com> wrote:

> The actual backup and restore process seems to be functioning correctly on
> the latest version of N. I recall it being broken before, which is why I
> never got around to doing anything about it.
>
> The key automation is something I'll need to fix. Worst case scenario,
> users will need to enter the password on Android N.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/koush/support-wiki/issues/57#issuecomment-230337081>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASkMHw1Lcv7mpkl25eo2ceo5bSakPIubks5qSU7UgaJpZM4IiHtF>
> .
>
-- 
www.s-gabriel.com
instagram.com/simonpatrickgabriel

**Comment by rprimus** [comment]
Mon Jul  4 19:29:28 BST 2016

@koush 

I've installed today, and have not been able to have a successful backup.   It continually asks to set a backup password (as FS is encrypted),  then to enter the password or pin for the  encrypted FS.

I've not yet been in a position to attempt a restore.

**Comment by rprimus** [comment]
On Tue, Jul 05, 2016 at 07:17:47AM -0700, simongabriel wrote:
> @rprimus 
> 
> Have you attempted a restore? I'm wondering if it's worth me trying to get back on Android N and give it a shot.

Tue  5 Jul 2016 15:42:09 BST

@simongabriel

I've not yet attempted a restore.   Will do so
later on this evening (in 2 hours) and report
here.

-- 
-primus (Train yourself and be your own master.)
"First solve the problem, then code!"
Narrowness of experience leads to narrowness of imagination.
http://www.catb.org/esr/faqs/smart-questions.html
http://www.chiark.greenend.org.uk/~sgtatham/bugs.html

GPG Key: DB3FB476
Key fingerprint: B0FB C67E 2E7E 7032 7FE6  7FBC 28E9 2848 DB3F B476

**Comment by simongabriel** [comment]
That would be great, thank you very much. Keep me updated

On Tue, 5 Jul 2016 at 15:45 Richard Primus <notifications@github.com> wrote:

> On Tue, Jul 05, 2016 at 07:17:47AM -0700, simongabriel wrote:
> > @rprimus
> >
> > Have you attempted a restore? I'm wondering if it's worth me trying to
> get back on Android N and give it a shot.
>
> Tue 5 Jul 2016 15:42:09 BST
>
> @simongabriel
>
> I've not yet attempted a restore. Will do so
> later on this evening (in 2 hours) and report
> here.
>
> --
> -primus (Train yourself and be your own master.)
> "First solve the problem, then code!"
> Narrowness of experience leads to narrowness of imagination.
> http://www.catb.org/esr/faqs/smart-questions.html
> http://www.chiark.greenend.org.uk/~sgtatham/bugs.html
>
> GPG Key: DB3FB476
> Key fingerprint: B0FB C67E 2E7E 7032 7FE6 7FBC 28E9 2848 DB3F B476
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/koush/support-wiki/issues/57#issuecomment-230499289>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASkMHxlo9EahrWQjr_pCnQmY3JylteOXks5qSm3xgaJpZM4IiHtF>
> .
>
-- 
www.s-gabriel.com
instagram.com/simonpatrickgabriel

**Comment by rprimus** [comment]
On Tue, Jul 05, 2016 at 07:59:30AM -0700, simongabriel wrote:
> That would be great, thank you very much. Keep me updated

Tue  5 Jul 2016 23:33:56 BST

@simongabriel

I have just been able to perform a flawless successful
restore of an app.

-- 
-primus (Train yourself and be your own master.)
"First solve the problem, then code!"
Narrowness of experience leads to narrowness of imagination.
http://www.catb.org/esr/faqs/smart-questions.html
http://www.chiark.greenend.org.uk/~sgtatham/bugs.html

GPG Key: DB3FB476
Key fingerprint: B0FB C67E 2E7E 7032 7FE6  7FBC 28E9 2848 DB3F B476

**Comment by simongabriel** [comment]
It's also working flawlessly from internal storage restore. Perfect!

Thanks so much @koush

**Comment by koush** [comment]
Glad it worked out. Thanks for the bug reports.
