### ISSUE TITLE
Helium support backup to OwnCloud

### ISSUE THREAD

**Issue by simonspa** [koush/support-wiki#8]
Hi @koush 

thanks for the great app(s) and effort.
I have one enhancement request for Helium: I would love to see the possibility to backup directly to an ownCloud server instead of Google Drive or Box. Is this something that could be implemented?

Cheers, Simon

**Comment by aikeru** [comment]
As a paid helium app user, I support this request! :)

Thanks for writing amazing software Koush!

**Comment by simonspa** [comment]
With no comment?
I find this a bit poor.

**Comment by koush** [comment]
sorry, bulk closed everything super old. i didn't even realize people were opening bugs here. i was just using this repo for the wiki.

**Comment by AlBundy33** [comment]
@koush Is there a better place to submit bugs and feature requests related to helium?

**Comment by simonspa** [comment]
@koush it would be really nice to have some sort of support platform...
