### ISSUE TITLE
koushik you m@@@@@f##### ...... installed drivers and your crap app on pc STILL DOESNT RECOGNIZE DEVICE....B@@@C##D SAALE....MALWARE BANAATAA HAI...!!!!

### ISSUE THREAD

**Issue by HeliumIsMalware** [koush/support-wiki#90]
**koushik you m@@@@@f##### ...... installed drivers and your crap app on pc STILL DOESNT RECOGNIZE DEVICE....B@@@C##D SAALE....MALWARE BANAATAA HAI...!!!!******

**Comment by raywalters** [comment]
Hey fucktard. Learn to Internet and learn to Windows. Stop being an asshat. Check your porn downloads for malware first.
